# Generated by Django 5.2.8 on 2025-11-18 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='webpage',
            field=models.URLField(blank=True),
        ),
    ]
