# Generated by Django 5.2.8 on 2025-11-18 04:10

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplements', '0003_update_product_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='estimated_shipping',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AddField(
            model_name='purchase',
            name='estimated_taxes',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AddField(
            model_name='purchase',
            name='order_id',
            field=models.CharField(blank=True, help_text='Amazon Order Number', max_length=100),
        ),
        migrations.AddField(
            model_name='purchase',
            name='real_shipping',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AddField(
            model_name='purchase',
            name='real_taxes',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AddField(
            model_name='purchase',
            name='weight_lb',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Shipment weight in pounds', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
    ]
