# Generated by Django 5.2.8 on 2025-11-19 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplements', '0004_purchase_delivery_date_purchase_estimated_shipping_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='supplier',
        ),
        migrations.AddField(
            model_name='product',
            name='brand_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.DeleteModel(
            name='Supplier',
        ),
    ]
