# Generated by Django 5.2.8 on 2025-11-19 03:49

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplements', '0005_remove_purchase_supplier_product_brand_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='average_cost',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Weighted average cost across all cost layers', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AddField(
            model_name='product',
            name='last_purchase_cost',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Most recent purchase unit cost', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AddField(
            model_name='product',
            name='last_purchase_date',
            field=models.DateTimeField(blank=True, help_text='When last purchased', null=True),
        ),
        migrations.CreateModel(
            name='CostLayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_cost', models.DecimalField(decimal_places=2, help_text='Cost per unit from this purchase batch', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('quantity_remaining', models.DecimalField(decimal_places=2, help_text='How many units are left in this batch', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('original_quantity', models.DecimalField(decimal_places=2, help_text='Initial quantity from purchase', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date received (for FIFO ordering)')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_layers', to='supplements.product')),
                ('purchase_item', models.ForeignKey(blank=True, help_text='The purchase item that created this cost layer', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cost_layer', to='supplements.purchaseitem')),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['product', 'created_at'], name='supplements_product_82129c_idx')],
            },
        ),
    ]
