# Generated by Django 5.2.8 on 2025-11-19 04:00

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplements', '0006_product_average_cost_product_last_purchase_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='costlayer',
            name='allocated_logistics_per_unit',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Allocated shipping + taxes per unit', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AddField(
            model_name='costlayer',
            name='base_unit_cost',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Base product cost per unit (before logistics)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AddField(
            model_name='costlayer',
            name='logistics_allocated',
            field=models.BooleanField(default=False, help_text='Whether logistics costs have been allocated to this layer'),
        ),
        migrations.AlterField(
            model_name='costlayer',
            name='unit_cost',
            field=models.DecimalField(decimal_places=2, help_text='Total cost per unit (base + allocated logistics)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
    ]
