# Generated by Django 5.2.8 on 2025-11-19 04:06

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplements', '0007_costlayer_allocated_logistics_per_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseitem',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Discount applied to total item cost (not per unit)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
    ]
