# Generated by Django 5.2.8 on 2025-11-24 03:42

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplements', '0009_customer_sale_status_sale_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usd_to_gtq_rate', models.DecimalField(decimal_places=4, default=Decimal('7.7500'), help_text='Exchange rate: 1 USD = X GTQ', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))])),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'System Settings',
                'verbose_name_plural': 'System Settings',
            },
        ),
        migrations.AddField(
            model_name='costlayer',
            name='unit_cost_gtq',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total cost per unit in GTQ (converted from USD)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='costlayer',
            name='unit_cost',
            field=models.DecimalField(decimal_places=2, help_text='Total cost per unit in USD (base + allocated logistics)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
    ]
