# Generated by Django 5.2.8 on 2025-11-24 04:12

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplements', '0010_systemsettings_costlayer_unit_cost_gtq_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='current_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Current selling price in GTQ', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_price', models.DecimalField(decimal_places=2, help_text='Previous price in GTQ', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('new_price', models.DecimalField(decimal_places=2, help_text='New price in GTQ', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('changed_date', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='supplements.product')),
            ],
            options={
                'verbose_name': 'Price History',
                'verbose_name_plural': 'Price Histories',
                'ordering': ['-changed_date'],
            },
        ),
    ]
