# Generated by Django 5.2.8 on 2025-11-24 04:46

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplements', '0011_product_current_price_pricehistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleitem',
            name='unit_cost',
            field=models.DecimalField(decimal_places=2, default=0, help_text='FIFO cost calculated from cost layers', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
    ]
