# Generated by Django 5.2.8 on 2025-11-25 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplements', '0012_alter_saleitem_unit_cost'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('current_stock__gte', 0)), name='product_stock_non_negative'),
        ),
    ]
